# Generated by Django 2.2.6 on 2020-12-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='webresult',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
