# Generated by Django 2.2.6 on 2020-12-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201227_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webresult',
            name='url',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
    ]
